### PR TITLE
Update ssl mode parameter

### PR DESCRIPTION
**Pull request by satendrakumar**
Here is related doc https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#option_general_ssl-mode

### CODE REVIEW

**Comment by miztiik** [comment]
I am not sure, If i understand you PR correctly.
The documentation says, `--ssl` parameter is much like **legacy** usage

How does this PR improve the situation?

**Comment by satendrakumar** [comment]
@miztiik `--ssl-mode=REQUIRED` . it is not working with Mysql 5.7.12+

**Comment by miztiik** [comment]
I had a quick look at [wiki](https://en.wikipedia.org/wiki/MySQL), 5.7.x is 4+ years old and still supported. I wouldn't prefer updating the readme without looking to support the newer syntax.

Can you @satendrakumar  re-submit your PR with updates to mention that for older version the parameter can be used as `--ssl=1`

**Review by miztiik — CHANGES_REQUESTED** [review]
Can you re-submit your PR with updates to mention that for older version the parameter can be used as `--ssl=1`

**Pull request closed without merging**
